### PR TITLE
Add some debug info to uniqueness check

### PR DESCRIPTION
**Pull request by napowderly**

### CODE REVIEW

**Review by mawildoer — APPROVED** [review]

**Review by mawildoer — CHANGES_REQUESTED** [review]
Actually, this will be formatted slightly strangely. It should be the address rather than the instance itself

**Comment by napowderly** [comment]
> Actually, this will be formatted slightly strangely. It should be the address rather than the instance itself

Screenshot 2024-03-19 at 11 21 29 AM

**Review by napowderly — COMMENTED** [review]
Modified to show address

**Comment by napowderly** [comment]
> Actually, this will be formatted slightly strangely. It should be the address rather than the instance itself

Fixed

**Review by mawildoer — APPROVED** [review]

**Pull request merged**
